graph LR
    CH[Handler Interface] --> M
    CP[Parer Interface] --> M
    CE[Engine Interface] --> M
    CV[View Interface] --> M

    IH[Handler Module] --> CH
    IP[Parser Module] --> CP
    IE[Engine Module] --> CE
    IV[View Module] --> CV

    M[Main]


subgraph ML[Modular Layer]
    IH
    IP
    IE
    IV
    subgraph CL[Interface Layer]
        CH
        CP
        CE
        CV
        subgraph OL[Orchestrator Layer]
            M
end
end
end